### ISSUE TITLE
【開発】環境構築に関する整理（プラットフォーム編）

### ISSUE THREAD

**Issue by urashin** [urashin/micro-volunteer-docs#4]
#3 

#### todo
- awsでの構築方法
  - - [x] dockerファイルの作成
  - - [x] 構築手順作成
- aws新規インスタンスでの動作確認
  - - [ ] ユーザー登録
  - - [ ] checkin, help
  - - [ ] LINE通知(help)
  - - [ ] LINEからのaccept
  - - [ ] ボランティア履歴表示

**Comment by urashin** [comment]
@1n-mas 時間のあるときで大丈夫なので、現状のdockerファイルと構築手順をcommitしていただけますか？動作確認は私の方で行います。

**Comment by 1n-mas** [comment]
> @1n-mas 時間のあるときで大丈夫なので、現状のdockerファイルと構築手順をcommitしていただけますか？動作確認は私の方で行います。

既にSlackで連絡していますが、Docker・構築手順　Commit済みです。
