### ISSUE TITLE
【サービス：仮説検証】障がい者が困る状況に関するインタビュー前の調査

### ISSUE THREAD

**Issue by urashin** [urashin/micro-volunteer-docs#7]
#2 
調査対象の課題を絞り込むために手持ちのソリューションをベースに仮説を設定する。
- ゴール
  - 1/27のインタビューで検証すべき項目（質問項目）が出そろう
- 仮説
  - 本サービスと相性の良さそうな課題とはどのようなものか？
    - 他人が介在することで簡単に解決できる
    - 障がい者にとっては比較的大きな問題
      - 解消しない場合
        - 成果をあきらめる
        - 多大な労力や時間がかかる 
    - 本サービスが代替え手段として選ばれる基準
      - 現状の解決手段 or 解決しなかった場合のデメリットが本サービス利用時のデメリット（ヘルプが駆けつけるまでの待機時間など）をおおきく上回る
  - 相性の良い課題が持つ要素とは何か？
    - 通常、他人の助けを得て解消している
    - サポートする側の肉体的負担がそこまでおおきくない
    - 短時間で解消する
    - 助けが来ることがわかっていれば、５分くらい待てる
- 調査方法
  - 以下の事例集をベースにデスクトップリサーチを行う
    - [事例集１](https://www.pref.osaka.lg.jp/attach/19846/00000000/touzisyaservicewish.pdf)
    - [事例集２](https://www.pref.toyama.jp/documents/3239/01292293.pdf)
    - [事例集３](https://www.city.nagoya.jp/kurashi/category/22-2-0-0-0-0-0-0-0-0.html)
- 検証項目
  - 事前調査をもとに仮説を作る
    - 本サービスと相性の良さそうな課題
    - これまで高コスト（手間、時間、金額、心理的負担）だったものが、本サービスを使うと低コストで済みそう
    - これまで諦めていたものが、本サービスを使うと解決する見込みがある
  - インタビューによる検証観点
    - 予想ではなく体験をきく
      - 実際にコスト（手間、時間、金額、心理的負担）を支払って解消していたかどうか（実体験）
      - どの程度の頻度で発生しているのか（実体験）
    - やむを得ず予想を聞く場合は具体的な金額、時間、数値を提示する

**Comment by THayashi0000** [comment]
◆仮説に該当しそうな障害例（候補）
- 商品が置かれている棚の高いところは、見えにくい。棚が高くて困った。車いすの高さに商品を置いて欲しい。 [車椅子]
- 美容室で髪を切るのに、注文しても通じない。手話ができるスペシャリストがいる。 [聴覚障害者]
- 車いすが通れないので商品を見ることが出来ない。 [車椅子]
- 買い物での付添サービス[視覚障害]
- デパートやレストラン手話のできる店員がほしい[聴覚障害]

◆利用場面の所感
- 日常生活の困ったことはお店等のサービス提供者が解決対応すべき問題が多い
- バリアフリーのような障害者を社会として意識すべき必要ラインの気がする
- そのため、互助共助からずれたボランティアで対応すべきではない印象を持つ

◆仮説に対して修正が必要な点
- 健常者が短時間で解消できる問題は、障害者が5分待たず、諦めるか周囲の人へ声をかけるのが自然
→健常者が短時間で解決できる問題でなく10〜30分ほどで解決できる課題が良さそう
→ガイド・ヘルプなど

◆その他
- 解決サービスイメージ：Uberの障害者支援ボランティア版

◆補足情報
- [ガイドヘルパー](https://prtimes.jp/main/html/rd/p/000000002.000078465.html)
→ガイドヘルパーのボランティアに絞ってサービス提供するのもあり？

**Comment by urashin** [comment]
ガイドヘルパーそのものであれば、既存のマッチングプラットフォームで解消できるので、あえてそこに入る必要性はなさそう。そこで解消できていない問題か、別の方向性を探る必要がある？

３通りの方向性を探ってみる
- ガイドヘルパーの軽めのサポートなどのニーズがあるかどうか
- 遠隔サポートのニーズを探る
- まずは店員につかってもらう or 店の対応コストを下げる何らかの方法を探る

**Comment by urashin** [comment]
店側視点をかんがえる際、障がい者支援をうたっている企業などが運営する店舗への導入から考えることができるか？
- [イオン](https://www.aeon.info/company/message/magazine/pdf/vol64.pdf)

類似サービス
- [&Hand](https://www.andhand-project.com/)

**Comment by urashin** [comment]
&Handが数年前から類似サービスに関する実証実験をやっているが、それ以降の情報更新がない。
- 仮に、何らかの障壁があって実証実験以降に進めない場合、要因として何が考えられるか？
  - 空港：おそらく、利用頻度が低い
  - 地下鉄：かならずしも周りにユーザーがいないため、マッチングが難しい

おそらく、利用頻度が高く（日常的に使う施設など）で、初期のマッチングの問題を解消できる状況を探る必要がある。
- 解決案
  - 概要：スーパー、コンビニにおける店員と障がい者のコミュニケーションをネットとリアル（臨場）の両面でサポートで解消する
  - 想定シーン
    - スーパーで手話が通じない場合、ビデオ通話で遠隔の支援者に店員とのコミュニケーションを媒介してもらう
  - 構成案
    - ネットサポート：マッチング成立を向上させるための仕組み
      - 市民参加のサポーター
        - 基本はこちらでまわす
      - 常駐の専門サポーター
        - 参加する市民が少ない最初の立ち上げでは常駐を数名用意して必ず繋がるようにしておく
    - リアルサポート：多少難しい問題の解決を支援する仕組み
      - ネットサポートで解消しない問題を近くにいるサポーターが現地に向かいサポートする

上記がそのまま最適解になるとは思えないが、方向性としては通常のサービスを行う人と、障がい者の間に障がい者固有の問題を解消する専門性の高い人をネットとリアルの両面で間に入れる体制を現実的に作れて、障がい者にとって満足度の高い種類の問題はどんな問題なのかを考える。

**Comment by THayashi0000** [comment]
◆ヒアリング目的
  - マイクロボランティアのソリューションがProblemにFitするか確認するため
  - 日常生活での障害者の方の課題が何かを確認するため

◆ ヒアリングを通して明らかにしたい点
  - 障害者の方が、日常生活でどのようなことに支援を求めることが多いか
  　仮説) 日常生活において、急に30分から1時間のボランティア支援が必要となるケースが多いのではないか？
　　ex) 一人で買い物に行く際、現地到着して初めて支援が必要でないといけないことを知る

  -  障害者の方が、日常生活で支援をお願いできない困りごとはないか？
  　（障害者支援の人にとって、障害者の方から困りごととして相談されるが、解決できていない課題はないか？）
     仮説）娯楽系の困りごとであれば、障害者支援者にお願いできないのではないか？
　  ex)視覚障害者の方が音楽が趣味で、リコメンドを探したいが、目が見えないのでITサービスを使えない

◆懸念点
  - 支援施設の利用者は高齢者が多い？
  - そもそも障害者に記入を依頼しているサービス等利用計画案そのものを書くことが負担？

◆本音（備考）
- やはりサービス等利用計画の内容が気になる
- サービス等利用計画自体がデジタル化できれば、データドリブンで課題抽出できるのに...

**Comment by THayashi0000** [comment]
◆ ヒアリングを通して聞きたい点（一点追加して更新）
障害者の方が、日常生活でどのようなことに支援を求めることが多いか
   - 仮説) 日常生活において、急に30分から1時間のボランティア支援が必要となるケースが多いのではないか？
   - ex) 一人で買い物に行く際、現地到着して初めて支援が必要でないといけないことを知る

障害者の方が、日常生活で支援をお願いできない困りごとはないか？
≒障害者支援の人にとって、障害者の方から困りごととして相談されるが、解決できていない課題はないか？
   - 仮説）娯楽系の困りごとであれば、障害者支援者にお願いできないのではないか？
   - ex) 視覚障害者の方が音楽が趣味で、リコメンドを探したいが、目が見えないのでITサービスを使えない
   
 障害者の方が、地域住民と接するときに生じる大きな壁はなにか？
   - そもそもどういう場面で一般の地域住民とコミュニケーションしたいか確認する必要あり
   - 仮説）障害者にとって一般人へ声をかけるハードルを高く感じ、きっかけさえあれば声をかけやすくなるのではないか？
   - ex) 視覚障害者の方がセミナー等参加の際、周囲の人へ話しかけたいが、ハードルが高く声をかけづらい
     
 ◆その他
    - ユーザヒアリング準備参考[URL](https://startup-city-sapporo.com/knowledge/user-hearing/)

**Comment by urashin** [comment]
現在出ている障がい者の「困りごと」に関する仮説は大きく分けて２つあり、
- 一瞬手伝うだけで、短時間で解消するような困りごと
- 30分〜１時間といった長時間の滞在が必要な困りごと


それぞれの場合について、以下の調査が必要
- 顕在化した課題か潜在的な課題か
  - 顕在化した課題であれば、資料を提示する必要がある
  - 潜在的な課題であれば、具体的な検証手段を提示を提示する必要がある
- 課題の価値の測定
  - 現在、それらはどのように解消されているのか？
  - 解消されない場合、どのような負担となるのか？ 
- マッチングのハードルを事前に洗い出しておく
  - ボランティア側から見たマッチングのハードル
    - 30分、１時間も付き添いができるか？できる状況や出来る人、完全な付き添いではない中間程度の付き添いの可能性
  - 障がい者側から見たマッチングのハードル
    - マッチング成立まで待てるか？待てないのであれば、待たずに済む工夫ができるか？

**Comment by THayashi0000** [comment]
仮説
1. 一瞬手伝うだけで、短時間で解消するような困りごと（解決手段が明確）
　・ショッピング中にたかいところに手が届かない（店員を呼ぶ、周りの人に頼む）
　・手話が通じない（レジで）（店員に筆談をお願いする、応じてもらえない：どんなケース？店員が忙しい？人柄？）
　・店の前の段差を車椅子で乗り越えられない（周りの人に押してもらう）
　・電話で予約をとりたいとき：聴覚障害（仮説）
2. 30分〜１時間といった長時間の滞在が必要な困りごと（解決手段が明確）
　・店内のショッピングで付き添い＆商品説明が欲しい：視覚障害
　・行ったことのない場所に初めていくとき：視覚障害（用事の種類とか確認したい、おそらくガイドヘルパーを使う）（仮説）
　・何かの申請をしなければならないとき：視覚障害（家族に頼む、ガラケーでどこかに依頼？）（仮説）
　
3. 障害者の方が、日常生活で支援を求めることができない困りごと（解決手段が明確ではない）
　・結婚相手を見つけたい（例えばマッチングアプリは視覚障害のかたが使えないとか）（仮説）
　・旅行に行きたい場合（車椅子等）（仮説）
4. 障害者の方が、地域住民と接するときに生じる大きな壁がある（解決手段が明確ではない、心理的障壁）
　・レジに時間がかかり、後ろに並んでいる人を気にしてしまう
　・音の出ない信号機で、横断する際に周りの人に「一緒にわたってもらう」ことを頼めず、１つ２つ先の音の出る信号機のある横断歩道を利用する。


（仮説）については事実としてあるかどうか、（仮説）がないものはアンケートなどから取得したもので、どの程度の課題の価値があり、どれほどのコスト（お金、手間、時間）をかけて解決したいのかを確認する。

**Comment by urashin** [comment]
【資料】

視覚障害
https://www.royal-co.net/column/store-safety-management/consideration-for-visually-impaired/

ガイドヘルパー
http://isee-movement.org/real/life
「残念ですが、課題もあります。ガイドヘルパーを利用するには事業所に登録し、予約をしないといけないので、急な外出には間に合わないということがあるようです。また、1ヶ月の利用時間数に制限があり、計画的に利用しないといざというとき外出できません。利用料がかかるため「経済的負担が増えた」という声もあります。」

[ガイドヘルパーの資格](https://www.ekaigotenshoku.com/ekaigowith/2019/12/10/guidehelper_shikaku/#:~:text=%E8%A6%96%E8%A6%9A%E9%9A%9C%E5%AE%B3%E8%80%85%E3%82%AC%E3%82%A4%E3%83%89%E3%83%98%E3%83%AB%E3%83%91%E3%83%BC%E3%81%AF%E3%80%81%E9%9A%9C%E5%AE%B3%E8%80%85%E7%B7%8F%E5%90%88%E6%94%AF%E6%8F%B4,%E3%81%AA%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82)

無料でも資格は必要か？

**Comment by urashin** [comment]
# 仮説・検証

## 仮説
- 本サービスと相性の良さそうな課題
  - 他人が介在することで簡単に解決できる
  - 障がい者にとっては比較的大きな問題
    - 解消しない場合
      - 成果をあきらめる
      - 労力や時間がかかる 
  - 本サービスが代替え手段として選ばれる基準
    - 現状の解決手段 or 解決しなかった場合のデメリットが本サービス利用時のデメリット（ヘルプが駆けつけるまでの待機時間など）をおおきく上回る
- 相性の良い課題が持つ要素とは何か？
  - 通常、他人の助けを得て解消している
  - サポートする側の肉体的負担がそこまでおおきくない（ただし、それなりの力仕事であっても周囲が助ける文化を持つ地域は存在する）
  - 短時間で解消する（長時間の拘束が必要なサービスは競合が存在するため、別の動機付けが必要）
  - 助けが来ることがわかっていれば、２，３分待てる
- 調査方法
  - 以下の事例集をベースにデスクトップリサーチを行う
    - [事例集１](https://www.pref.osaka.lg.jp/attach/19846/00000000/touzisyaservicewish.pdf)
    - [事例集２](https://www.pref.toyama.jp/documents/3239/01292293.pdf)
    - [事例集３](https://www.city.nagoya.jp/kurashi/category/22-2-0-0-0-0-0-0-0-0.html)
- 検証項目に関する考え方
  - 事前調査をもとに仮説を作る
    - 本サービスと相性の良さそうな課題
    - これまで高コスト（手間、時間、金額、心理的負担）だったものが、本サービスを使うと低コストで済みそう
    - これまで諦めていたものが、本サービスを使うと解決する見込みがある
  - インタビューによる検証観点
    - 予想ではなく体験をきく
      - 実際にコスト（手間、時間、金額、心理的負担）を支払って解消していたかどうか（実体験）
      - どの程度の頻度で発生しているのか（実体験）
    - やむを得ず予想を聞く場合は具体的な金額、時間、数値を提示する

## 検証項目
- 解決手段が明確な課題
  - 短時間で解決する課題
    - ショッピング中に高いところに手が届かない
      - とどかなかった場合、結局どうしているのか？
      - ショッピングに出かける際、これが原因ででかけることを諦めるor行き先を変えることはあるのか？
    - 店員が筆談で対応してくれると買い物しやすいと思う。聞こえないと言っても口で話し、筆談してくれなくて困った。
      - どのような状況で筆談におうじてくれないのか？
        - 忙しいから？
        - 店員の人柄？
    - 代筆が認められず困った。
      - そのようなケースでは、結局どうする？
      - どのような場合に代筆が認められないのか？
    - 手話通訳者の利用範囲を広げて欲しい。 
      - このような[遠隔手話サービス](https://shur.jp/business.html)は使えないのか？
    - デパートやレストラン手話のできる店員がほしい[聴覚障害]
      - 手話で店員に伝えたいことはどのような用事か？
      - 手話ができる店員がいない場合、どうしているのか？
     

  - 長時間の付き添い(30分〜1時間）が必要な課題
    - 既存のマッチングサービスでは解消しない課題とはどのようなものか？
      - おそらく利用時間の制限に入りきらないものが「解消しない課題」となりそう
    - ガイドヘルパー([a](https://www.careshikaku.com/guidehelper_guide/guidehelper_shikaku) , [b](https://www.ekaigotenshoku.com/ekaigowith/2019/12/10/guidehelper_shikaku/#:~:text=%E8%A6%96%E8%A6%9A%E9%9A%9C%E5%AE%B3%E8%80%85%E3%82%AC%E3%82%A4%E3%83%89%E3%83%98%E3%83%AB%E3%83%91%E3%83%BC%E3%81%AF%E3%80%81%E9%9A%9C%E5%AE%B3%E8%80%85%E7%B7%8F%E5%90%88%E6%94%AF%E6%8F%B4,%E3%81%AA%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82))や、[既存のマッチングサービス](https://prtimes.jp/main/html/rd/p/000000002.000078465.html)では解消せず、本サービスであれば解消する課題はあるか？差分が生じる原因は何か？
      - 当日、直前でもマッチングできる
        - インタビューでの確認ポイント
          - 当日、直前のニーズがどれくらいあるか？
          - どのような用事であれば相性がよいか？
          - 制度面で、障害者支援に制限はあるのか？
            - 資格がないと、何ができないのか？

- 解決手段が不明確な課題
  - どのようなものがあるのかを確認
    - 仮説
      - 結婚相手を見つけたい（例えばマッチングアプリは視覚障害のかたが使えないとか）
      - 旅行に行きたい場合（車椅子等）

**Comment by urashin** [comment]
インタビュー結果からみえてきたことのまとめ（このサービスと相性の良さそうな深掘り対象課題）
- 短時間の用事＆突発的＆瞬間的なマッチングが必要
  - 車椅子：サポートを受けなくてもある程度自分で移動が可能なため、日常的な困りごとに遭遇しやすい。
  - 精神障害：外出中に想定外の問題に遭遇すると、適切に周りに助けを求めることができず、パニックになる人もいる
- 長時間の用事＆突発的＆当日中だが数十分のマッチング猶予がある
  - 視覚障害：ルーティンワークのようなものや、予め予定が立てられる用事については事前にサポートを依頼できるが、夜中に病院にいかなければならないような突発的な問題の場合はサポートを受けられず困ることがある

**Comment by urashin** [comment]
このインタビューに関しては完了
